(()=>{
const N=45,$=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),fmt=(v,d=1)=>Number(v).toFixed(d);
const cropFactor={F:.25,P:.90,'1R':1.00,'2R':1.05,'3R':1.02,'4R':.95};
const cropRank={F:0,P:1,'1R':2,'2R':3,'3R':4,'4R':5};
const REGIONS={
 tablelands:{title:'Atherton Tablelands',query:'Atherton Tablelands Queensland Australia'},
 mackay:{title:'Mackay / Eton',query:'Eton Queensland Australia'},
 burdekin:{title:'Burdekin',query:'Burdekin Shire Queensland Australia'}
};
const S={
 tablelands_cp:{name:'Tablelands — Centre Pivot',region:'tablelands',water:'unlimited',system:'Centre Pivot',code:'CP',pump:40,energy:'Electric',hours:24,cycle:4,application:32.2554,areaTotal:40.715,area:10.17876,scheduling:'IrrigWeb',automation:'Yes',trigger:60,allocation:null,layout:'CP1 · Harvest Year 1',crops:['F','P','1R','2R'],imuNames:['IMU 1','IMU 2','IMU 3','IMU 4'],summary:'One 40 L/s centre pivot divided into four equal-quarter IMUs. This is the cleanest Forecast OFF vs ON experiment.',detail:'Steve’s CP worksheet: 4 equal-quarter IMUs, 24 h per irrigation, 4-day minimum cycle, 95% application efficiency and about 32.3 mm net application.',note:'Workbook source: CP sheet. Fallow is not irrigated. The CP sheet tests Weather forecast = No vs Yes while IrrigWeb and automation remain Yes.'},
 mackay_cp:{name:'Mackay / Eton — CP IrrigWeb test',region:'mackay',water:'unlimited',system:'Centre Pivot',code:'CP',pump:40,energy:'Electric',hours:24,cycle:4,application:32.3,areaTotal:40.715,area:10.17876,scheduling:'IrrigWeb',automation:'Yes',trigger:60,allocation:null,layout:'Clover_Mky · 2021 crop classes',crops:['P','1R','2R','3R'],imuNames:['CP1_B1','CP1_B2','CP1_B3','CP1_B4'],summary:'Uses the same farm structure as Steve’s existing Mackay/Eton IrrigWeb Forecast Yes/No test.',detail:'Eton Sunwater met site, Black Earth PAW 170 mm, 4 CP IMUs, 34 mm gross / 32.3 mm net irrigation and 4-day minimum cycle.',note:'Workbook source: IrrigWeb test sheet. The benchmark results shown above are actual workbook values; this web simulation below still uses synthetic weather.'},
 tablelands_lm:{name:'Tablelands — Lateral Move',region:'tablelands',water:'unlimited',system:'Lateral Move',code:'LM',pump:50,energy:'Diesel',hours:24,cycle:6,application:40,hydraulicNet:51.818,areaTotal:47.52,area:7.92,scheduling:'IrrigWeb',automation:'Yes',trigger:60,allocation:null,layout:'LM · Harvest Year 1',crops:['F','P','1R','2R','3R','4R'],imuNames:['IMU 1','IMU 2','IMU 3','IMU 4','IMU 5','IMU 6'],summary:'Six IMUs under one 50 L/s lateral move. The longer 6-day cycle makes forecast timing more operationally important.',detail:'Steve’s LM worksheet: 6 IMUs, 24 h per irrigation, diesel energy, IrrigWeb scheduling and automation. Hydraulic net is about 51.8 mm, while the management strategy says apply a maximum 40 mm.',note:'Workbook source: LM sheet. Fallow is not irrigated. The 40 mm management target is used in this demo rather than the full 51.8 mm hydraulic capacity.'},
 mackay_traveller:{name:'Mackay — Overhead traveller',region:'mackay',water:'limited',system:'Overhead traveller',code:'Traveller',pump:30,energy:'Not specified',hours:13,cycle:11,application:30.4185,areaTotal:33.0016,area:3.00015,scheduling:'Fixed cycle',automation:'Manual',trigger:60,allocation:2.80786,layout:'11-IMU farm-layout example · Harvest Year 1',crops:['F','F','F','1R','1R','1R','1R','3R','3R','3R','3R'],imuNames:Array.from({length:11},(_,i)=>`IMU ${i+1}`),summary:'A genuinely water-limited Mackay case: 11 small IMUs, one 30 L/s traveller and about 2.81 ML/ha in the workbook setup.',detail:'Steve’s Farm set up sheet: 11 IMUs of about 3.0 ha, 13 h per irrigation, about 30.4 mm net per irrigation, 11-day cycle and night-time irrigation.',note:'Workbook source: Farm set up plus the 11-IMU Farm layouts example. Notes also describe about 3 ML/ha in the Eton Irrigation Scheme. Crop classes use the reduced-variation 11-IMU layout example.'},
 burdekin_furrow:{name:'Burdekin — Furrow',region:'burdekin',water:'unlimited',system:'Furrow',code:'Furrow',pump:55,energy:'Not specified',hours:24,cycle:7,cycleInferred:true,application:110.866,areaTotal:30.00375,area:4.28625,scheduling:'Fixed cycle',automation:'Manual',trigger:60,allocation:null,layout:'7-IMU hydraulic-group example · Harvest Year 1',crops:['F','F','F','F','1R','1R','1R'],imuNames:Array.from({length:7},(_,i)=>`IMU ${i+1}`),summary:'A broader-system example showing how the CLOVER logic may transfer beyond precision overhead irrigation.',detail:'Steve’s Farm set up sheet: 55 L/s furrow system, 7 IMUs of about 4.29 ha and about 110.9 mm net per irrigation.',note:'Workbook does not state a minimum cycle for furrow. This demo infers 7 days from 7 IMUs × 24 h per irrigation and labels that assumption explicitly.'}
};
const LEVELS={
 1:{eye:'LEVEL 1 — UNDERSTAND CLOVER',title:'See exactly what the forecast changes',text:'Start with Steve’s simplest controlled CP setup. Baseline and CLOVER use the same IMUs, crop classes, pump, scheduling, automation and realised weather. Only CLOVER can delay an irrigation when a qualifying short-term rainfall forecast appears.',q:'Farmer question: “If useful rain is coming soon, can I safely wait instead of irrigating today?”'},
 2:{eye:'LEVEL 2 — EXISTING EVIDENCE',title:'Connect the decision logic to Steve’s IrrigWeb example',text:'The top panel shows Steve’s actual Mackay/Eton workbook results. The simulator underneath uses the same 4-IMU setup but synthetic rainfall so we can watch how the decision develops day by day.',q:'Farmer question: “Has this kind of forecast decision already shown an irrigation saving in our modelling?”'},
 3:{eye:'LEVEL 3 — FARMER VALUE',title:'Show the two different reasons a farmer might care',text:'Switch between a non-limited Tablelands CP and a limited-water Mackay traveller. The first emphasises irrigation/pumping avoided; the second emphasises preserving scarce allocation and reducing water stress.',q:'Two different stories: efficiency when water is available; resilience when water is limited.'},
 4:{eye:'LEVEL 4 — FARM SYSTEMS',title:'Put the same CLOVER idea into different irrigation systems',text:'Compare Steve’s Centre Pivot, Lateral Move, overhead traveller and furrow setups. The IMU count, area, application depth and hydraulic cycle all change, so the same forecast can have a different practical consequence.',q:'Farmer question: “Does this still make sense for the irrigation system I actually use?”'},
 5:{eye:'LEVEL 5 — FULL CLOVER',title:'Add pump capacity and decide which IMU goes first',text:'Now several IMUs can need water at the same time, but the farm has only one irrigation slot. CLOVER combines forecast delay with a selectable priority rule to decide which IMU receives that slot.',q:'Farm-management question: “When I cannot irrigate everything today, what should go first — and should any block wait for rain?”'}
};
const EVIDENCE=[
 {imu:'CP1_B1',crop:'P',yes:782,no:850,yYes:160,yNo:160,save:68,pct:8.0},
 {imu:'CP1_B2',crop:'1R',yes:496,no:578,yYes:118,yNo:119,save:82,pct:14.19},
 {imu:'CP1_B3',crop:'2R',yes:632,no:680,yYes:133,yNo:134,save:48,pct:7.06},
 {imu:'CP1_B4',crop:'3R',yes:502,no:612,yYes:130,yNo:131,save:110,pct:17.97}
];
let state={level:1,scenario:'tablelands_cp',value:'nonlimited',system:'tablelands_cp',priorityScenario:'tablelands_cp',priorityRule:'swd',seed:1056,weather:[]};
function rng(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function gauss(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function genWeather(){const r=rng(state.seed);state.weather=[];for(let i=0;i<N;i++){const event=r()<clamp(.15+.10*Math.sin((i+3)/5.2),.05,.29);let actual=event?Math.max(0,5+r()*27+gauss(r)*4):(r()<.08?r()*4:0);let fc=Math.max(0,actual*(.65+r()*.75)+gauss(r)*4.5);let prob=actual>5?52+r()*43:12+r()*53;if(r()<.1)prob=66+r()*28;if(actual>15&&r()<.1)prob=30+r()*30;state.weather.push({day:i,actual:+actual.toFixed(1),fc:+fc.toFixed(1),prob:Math.round(clamp(prob,5,95)),etc:+clamp(5.4+Math.sin(i/6)+gauss(r)*.7,3.6,7.4).toFixed(1)})}}
function date(i){return new Date(2026,8,7+i).toLocaleDateString('en-AU',{day:'2-digit',month:'short'})}
function forecastSignal(day,p){let best=null;for(let k=0;k<p.look;k++){const w=state.weather[day+k];if(!w)break;if(w.fc>=p.rain&&w.prob>=p.prob&&(!best||w.fc*w.prob>best.fc*best.prob))best={...w,ahead:k}}return best}
function choose(cands,rule){if(!cands.length)return null;const copy=[...cands];if(rule==='fixed')return copy.sort((a,b)=>a.i-b.i)[0];if(rule==='cropAge')return copy.sort((a,b)=>cropRank[b.crop]-cropRank[a.crop]||b.swd-a.swd||a.i-b.i)[0];if(rule==='stress')return copy.sort((a,b)=>b.stress-a.stress||b.swd-a.swd||a.i-b.i)[0];return copy.sort((a,b)=>b.swd-a.swd||a.i-b.i)[0]}
function params(sc){return{tr:+$('trigger').value,rain:+$('rainThreshold').value,prob:+$('probThreshold').value,look:+$('lookahead').value,force:+$('trigger').value+20,allocation:sc.water==='limited'?+$('allocation').value:Infinity}}
function initialSwd(i,crop){if(crop==='F')return 28+(i%3)*3;return 40+((i*7+cropRank[crop]*3)%20)}
function simulate(sc,smart,p,rule){
 const imus=sc.crops.map((crop,i)=>({i,name:sc.imuNames[i],crop,area:sc.area,swd:initialSwd(i,crop),last:-999,stress:0,irrig:0,effRain:0,effIrr:0,lossIrr:0,left:sc.water==='limited'?p.allocation*100:Infinity,changed:0}));
 const avg=[],events=[],queues=[];let farmIrrML=0,farmEffRainML=0;
 for(let d=0;d<N;d++){
  const w=state.weather[d],sig=forecastSignal(d,p),due=[];
  imus.forEach(m=>{m.swd+=w.etc*cropFactor[m.crop];if(m.crop!=='F'&&m.swd>=p.tr&&d-m.last>=sc.cycle&&m.left>.01)due.push(m)});
  let candidates=due;
  if(smart){candidates=due.filter(m=>!(sig&&m.swd<p.force));due.forEach(m=>{if(sig&&m.swd<p.force)m.changed++})}
  const winner=choose(candidates,rule);
  if(due.length>1)queues.push({day:d,due:due.map(m=>m.name),candidates:candidates.map(m=>m.name),winner:winner?.name||'None',sig,rule});
  if(winner){const before=winner.swd,ap=Math.min(sc.application,winner.left);winner.irrig+=ap;winner.effIrr+=Math.min(ap,before);winner.lossIrr+=Math.max(0,ap-before);winner.swd=Math.max(0,before-ap);winner.last=d;if(isFinite(winner.left))winner.left-=ap;farmIrrML+=ap*winner.area*.01;events.push({day:d,imu:winner.name,type:'irrig',amount:ap})}
  else if(smart&&due.length&&sig)events.push({day:d,imu:due.map(x=>x.name).join(', '),type:'delay',amount:0});
  imus.forEach(m=>{const er=Math.min(w.actual,Math.max(0,m.swd));m.effRain+=er;m.swd=Math.max(0,m.swd-er);farmEffRainML+=er*m.area*.01;if(m.crop!=='F'&&m.swd>75)m.stress+=(m.swd-75)/25});
  const active=imus.filter(m=>m.crop!=='F');avg.push({day:d,swd:active.length?active.reduce((a,m)=>a+m.swd,0)/active.length:0});
 }
 return{imus,avg,events,queues,farmIrrML,farmEffRainML,stress:imus.reduce((a,m)=>a+m.stress,0),leftMLha:sc.water==='limited'?imus.filter(m=>m.crop!=='F').reduce((a,m)=>a+m.left,0)/Math.max(1,imus.filter(m=>m.crop!=='F').length)/100:null};
}
function currentScenario(){if(state.level===1)return'tablelands_cp';if(state.level===2)return'mackay_cp';if(state.level===3)return state.value==='limited'?'mackay_traveller':'tablelands_cp';if(state.level===4)return state.system;return state.priorityScenario}
function loadScenario(key){state.scenario=key;const sc=S[key];$('trigger').value=sc.trigger;$('allocation').value=sc.allocation??3;$('allocationGroup').classList.toggle('hidden',sc.water!=='limited');render()}
function renderLevel(){const l=LEVELS[state.level];$('levelEyebrow').textContent=l.eye;$('levelTitle').textContent=l.title;$('levelText').textContent=l.text;$('levelQuestion').textContent=l.q;$('heroBadge').textContent=`Level ${state.level} · ${S[currentScenario()].name}`;document.querySelectorAll('.level-tab').forEach(b=>b.classList.toggle('active',+b.dataset.level===state.level));$('evidencePanel').classList.toggle('hidden',state.level!==2);$('valuePanel').classList.toggle('hidden',state.level!==3);$('systemsPanel').classList.toggle('hidden',state.level!==4);$('priorityPanel').classList.toggle('hidden',state.level!==5);$('queueSection').classList.toggle('hidden',state.level!==5)}
function renderEvidence(){if($('evidenceGrid').children.length)return;$('evidenceGrid').innerHTML=EVIDENCE.map(e=>`<div class="evidence-item"><b>${e.imu} · ${e.crop}</b><span>Forecast OFF ${e.no} mm → ON ${e.yes} mm</span><div class="save">−${e.save} mm</div><span>${fmt(e.pct,1)}% less irrigation · Yield ${e.yNo} → ${e.yYes} t/ha</span></div>`).join('');$('evidenceSummary').innerHTML='<b>Workbook summary:</b> 31.35 ML total saved across the four IMUs, average 0.77 ML/ha, about 11.3% irrigation saving in the 2021 example. The workbook yields remain very similar between Forecast Yes and No.'}
function renderSystemPicker(){const items=[['tablelands_cp','Centre Pivot','4 IMUs · 40 L/s · 4-day cycle'],['tablelands_lm','Lateral Move','6 IMUs · 50 L/s · 6-day cycle'],['mackay_traveller','Traveller','11 IMUs · 30 L/s · 11-day cycle'],['burdekin_furrow','Furrow','7 IMUs · 55 L/s · cycle inferred']];$('systemPicker').innerHTML=items.map(([k,n,s])=>`<button class="system-card ${state.system===k?'active':''}" data-system="${k}"><b>${n}</b><span>${S[k].name}</span><div class="mini">${s}</div></button>`).join('');document.querySelectorAll('.system-card').forEach(b=>b.onclick=()=>{state.system=b.dataset.system;loadScenario(state.system)})}
function setMap(sc){const r=REGIONS[sc.region],q=encodeURIComponent(r.query);$('mapTitle').textContent=r.title;$('farmMap').src='https://www.google.com/maps?q='+q+'&output=embed';$('mapLink').href='https://www.google.com/maps/search/?api=1&query='+q}
function renderScenario(sc){$('scenarioName').textContent=sc.name;$('scenarioSummary').textContent=sc.summary;$('scenarioHeading').textContent=sc.name;$('scenarioDetail').textContent=sc.detail;$('waterTag').textContent=sc.water==='limited'?'Limited water':'Water non-limiting';$('systemTag').textContent=`${sc.system} · ${sc.scheduling}`;$('farmLayoutTitle').textContent=sc.layout;setMap(sc);const facts=[[`${sc.pump} L/s`,'Pump flow'],[`${sc.crops.length}`,'IMUs'],[`${fmt(sc.area,2)} ha`,'Area / IMU'],[`${fmt(sc.application,1)} mm`,'Net target'],[`${sc.cycle} d${sc.cycleInferred?'*':''}`,'Cycle'],[`${sc.hours} h`,'Per irrigation'],[sc.energy,'Energy'],[sc.automation,'Automation'],[sc.water==='limited'?`${fmt(sc.allocation,2)} ML/ha`:'Unlimited','Allocation']];$('factsGrid').innerHTML=facts.map(x=>`<div class="fact"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');$('workbookNote').textContent=sc.note}
function E(tag,a={},t=''){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));if(t)e.textContent=t;return e}function clear(s){while(s.firstChild)s.removeChild(s.firstChild)}
function dims(H,max,flip=false){const W=1100,L=48,R=18,T=22,B=38,pw=W-L-R,ph=H-T-B,x=i=>L+i*pw/(N-1),y=v=>flip?T+v/max*ph:T+ph-v/max*ph;return{W,H,L,R,T,B,pw,ph,x,y}}
function grid(svg,d,max,label){for(let g=0;g<=5;g++){const v=max*g/5,y=d.y(v);svg.append(E('line',{x1:d.L,y1:y,x2:d.W-d.R,y2:y,class:'gridline'}));svg.append(E('text',{x:d.L-8,y:y+3,'text-anchor':'end',class:'axistext'},Math.round(v)))}svg.append(E('text',{x:8,y:15,class:'axistext'},label));for(let i=0;i<N;i+=5)svg.append(E('text',{x:d.x(i),y:d.H-10,'text-anchor':'middle',class:'axistext'},date(i)))}
function path(vals,x,y){return vals.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v).toFixed(1)).join(' ')}
function rainChart(p){const svg=$('rainChart');clear(svg);const m=Math.max(45,...state.weather.map(w=>Math.max(w.fc,w.actual))),d=dims(280,m),bw=Math.max(3,d.pw/N*.5);grid(svg,d,m,'mm');state.weather.forEach((w,i)=>{const q=w.fc>=p.rain&&w.prob>=p.prob;svg.append(E('rect',{x:d.x(i)-bw*.65,y:d.y(w.fc),width:bw*.55,height:d.y(0)-d.y(w.fc),rx:2,fill:q?'#8fc4a7':'#b9d6e9',opacity:.85}));svg.append(E('rect',{x:d.x(i),y:d.y(w.actual),width:bw*.55,height:d.y(0)-d.y(w.actual),rx:2,fill:'#3e83b7'}))});const y=d.y(p.rain);svg.append(E('line',{x1:d.L,y1:y,x2:d.W-d.R,y2:y,stroke:'#2f8f63','stroke-dasharray':'4 5'}));svg.append(E('text',{x:d.L+5,y:y-5,class:'axistext'},`forecast gate: ≥${p.rain} mm & ≥${p.prob}%`))}
function swdChart(b,c,p){const svg=$('swdChart');clear(svg);const m=Math.max(110,p.force+20,...b.avg.map(r=>r.swd),...c.avg.map(r=>r.swd)),d=dims(280,m,true);grid(svg,d,m,'SWD mm');const tr=d.y(p.tr),fo=d.y(p.force);svg.append(E('line',{x1:d.L,y1:tr,x2:d.W-d.R,y2:tr,stroke:'#9eada5','stroke-dasharray':'6 5'}));svg.append(E('line',{x1:d.L,y1:fo,x2:d.W-d.R,y2:fo,stroke:'#d8a28d','stroke-dasharray':'3 5'}));svg.append(E('path',{d:path(b.avg.map(x=>x.swd),d.x,d.y),fill:'none',stroke:'#889a91','stroke-width':2.3}));svg.append(E('path',{d:path(c.avg.map(x=>x.swd),d.x,d.y),fill:'none',stroke:'#2f8f63','stroke-width':3}));svg.append(E('text',{x:770,y:17,class:'axistext'},'grey = Baseline farm average · green = CLOVER farm average'))}
function renderImus(sc,b,c){const maxS=Math.max(100,...b.imus.map(x=>x.swd),...c.imus.map(x=>x.swd));$('imuGrid').style.gridTemplateColumns=`repeat(${Math.min(4,sc.crops.length)},minmax(0,1fr))`;$('imuGrid').innerHTML=b.imus.map((m,i)=>{const x=c.imus[i],f=m.crop==='F';return`<div class="imu-card ${f?'fallow':''}"><div class="head"><div><div class="name">${m.name}</div><div class="crop">${m.crop}</div></div><div class="area">${fmt(m.area,2)} ha</div></div><div class="swd-bars"><div class="swd-label"><span>Baseline SWD</span><span>${fmt(m.swd,0)} mm</span></div><div class="bar base"><i style="width:${clamp(m.swd/maxS*100,0,100)}%"></i></div><div class="swd-label"><span>CLOVER SWD</span><span>${fmt(x.swd,0)} mm</span></div><div class="bar clover"><i style="width:${clamp(x.swd/maxS*100,0,100)}%"></i></div></div><div class="imu-meta">Irrigation ${fmt(m.irrig,0)} → ${fmt(x.irrig,0)} mm${f?' · fallow not irrigated':''}</div></div>`}).join('');$('farmCaption').textContent=`Crop classes come from ${sc.layout}. Synthetic crop-water demand uses demonstration factors (${Object.entries(cropFactor).map(([k,v])=>k+' '+v.toFixed(2)+'×').join(', ')}); these demand factors are not values from the workbook.`}
function renderKpis(sc,b,c){const irrSave=b.farmIrrML-c.farmIrrML,erGain=c.farmEffRainML-b.farmEffRainML,stressSave=b.stress-c.stress,changed=c.events.filter(e=>e.type==='delay').length,conflicts=c.queues.length;const cards=[['Irrigation difference',(irrSave>=0?'+':'')+fmt(irrSave,1)+' ML',`${fmt(b.farmIrrML,1)} → ${fmt(c.farmIrrML,1)} ML`,irrSave>=0?'good':'warn'],['Effective rain gain',(erGain>=0?'+':'')+fmt(erGain,1)+' ML',`${fmt(b.farmEffRainML,1)} → ${fmt(c.farmEffRainML,1)} ML`,erGain>=0?'good':''],['Stress reduction',(stressSave>=0?'+':'')+fmt(stressSave,1),`${fmt(b.stress,1)} → ${fmt(c.stress,1)} stress index`,stressSave>=0?'good':'warn'],[sc.water==='limited'?'Allocation left':'Forecast delays',sc.water==='limited'?`${fmt(c.leftMLha,2)} ML/ha`:`${changed}`,sc.water==='limited'?`CLOVER average remaining`:'irrigation decisions delayed',''],['Capacity conflicts',`${conflicts}`,state.level===5?'multi-IMU demand days':'days with >1 IMU due','']];$('kpiGrid').innerHTML=cards.map(x=>`<div class="panel kpi ${x[3]}"><div class="label">${x[0]}</div><div class="big">${x[1]}</div><div class="sub">${x[2]}</div></div>`).join('')}
function renderResults(sc,b,c){$('imuResults').innerHTML=b.imus.map((m,i)=>{const x=c.imus[i],d=m.irrig-x.irrig,er=x.effRain-m.effRain,st=m.stress-x.stress;return`<tr><td>${m.name}</td><td>${m.crop}</td><td>${fmt(m.area,2)} ha</td><td>${fmt(m.irrig,0)} mm</td><td>${fmt(x.irrig,0)} mm</td><td class="${d>0?'positive':d<0?'negative':''}">${d>=0?'+':''}${fmt(d,0)} mm</td><td class="${er>0?'positive':''}">${er>=0?'+':''}${fmt(er,1)} mm</td><td class="${st>0?'positive':st<0?'negative':''}">${st>=0?'+':''}${fmt(st,1)}</td></tr>`}).join('')}
function renderQueue(c){$('queueCount').textContent=`${c.queues.length} conflict days`;$('queueList').innerHTML=c.queues.slice(0,18).map(q=>{const sig=q.sig?` Forecast: ${q.sig.fc} mm @ ${q.sig.prob}% in ${q.sig.ahead} d.`:'';return`<div class="queue-item"><div class="date">${date(q.day)}</div><div class="queue">Due: ${q.due.join(', ')}${q.candidates.length<q.due.length?' · some delayed for forecast':''}</div><div class="winner">Slot → ${q.winner}</div><div class="reason">Rule: ${q.rule}.${sig}</div></div>`}).join('')||'<div class="farm-caption">No multi-IMU conflicts occurred in this synthetic weather run. Try New synthetic weather or adjust the SWD trigger.</div>'}
function render(){renderLevel();renderEvidence();renderSystemPicker();const key=currentScenario();state.scenario=key;const sc=S[key];$('allocationGroup').classList.toggle('hidden',sc.water!=='limited');$('triggerV').textContent=$('trigger').value;$('rainV').textContent=$('rainThreshold').value;$('probV').textContent=$('probThreshold').value;$('lookV').textContent=$('lookahead').value;$('allocationV').textContent=fmt($('allocation').value,2);renderScenario(sc);const p=params(sc);const baseRule='fixed',cloverRule=state.level===5?state.priorityRule:'fixed';const b=simulate(sc,false,p,baseRule),c=simulate(sc,true,p,cloverRule);renderImus(sc,b,c);renderKpis(sc,b,c);renderResults(sc,b,c);rainChart(p);swdChart(b,c,p);if(state.level===5)renderQueue(c);$('heroBadge').textContent=`Level ${state.level} · ${sc.name}`}
function switchLevel(level){state.level=level;if(level===1)loadScenario('tablelands_cp');else if(level===2)loadScenario('mackay_cp');else if(level===3)loadScenario(state.value==='limited'?'mackay_traveller':'tablelands_cp');else if(level===4)loadScenario(state.system);else loadScenario(state.priorityScenario)}
document.querySelectorAll('.level-tab').forEach(b=>b.onclick=()=>switchLevel(+b.dataset.level));document.querySelectorAll('.value-card').forEach(b=>b.onclick=()=>{state.value=b.dataset.value;document.querySelectorAll('.value-card').forEach(x=>x.classList.toggle('active',x===b));loadScenario(state.value==='limited'?'mackay_traveller':'tablelands_cp')});$('priorityScenario').onchange=e=>{state.priorityScenario=e.target.value;loadScenario(state.priorityScenario)};$('priorityRule').onchange=e=>{state.priorityRule=e.target.value;render()};['trigger','rainThreshold','probThreshold','lookahead','allocation'].forEach(id=>$(id).addEventListener('input',render));$('newWeather').onclick=()=>{state.seed=Math.floor(Math.random()*1e9);genWeather();render()};genWeather();renderEvidence();loadScenario('tablelands_cp');
})();
